apiVersion: v1
kind: Pod
metadata:
  name: staticweb
  labels:
     curso: edc
     app: meunginx
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - name: webports
      containerPort: 80
      protocol: TCP
