apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
  labels:
    app: meunginx
spec:
  replicas: 3
  selector:
     matchLabels:
        app: meunginx
  template:
    metadata:
      labels:
        app: meunginx
    spec:
     containers:
     -  name: webserver
        image: nginx
        ports:
          - containerPort: 80